server:
  port: 17601
spring:
  application:
    name: PollConfig

---
spring:
  profiles: default, dev
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/poll-demo-config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: production
  cloud:
    config:
      server:
        git:
          uri: file:///root/poll-demo-config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://poll-eureka:8761/eureka/
